name: Secrets

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        # Assume-se que os passos anteriores já estão definidos aqui.
    
    deploy:
        needs: build
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        steps:
            - name: Deploy to Production
              run: echo "Deploying to production server with token ${{ secrets.DEPLOY_TOKEN }}"
              # Substitua o comando acima pelo seu comando real de deploy, utilizando o secret conforme necessário.